<?php
namespace Api\Classes\Utilities\Filters;

class AppFilterProfileSanitize
extends AppFilters
{

	CONST OPTIONAL_VALUE  = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
		self::INPUT_SANITIZER['CLEAN_STRIPPED'],
		self::INPUT_SANITIZER['CLEAN_ENCODING'],
	];

	CONST NAME_GENERIC   = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
	];
	CONST ADDRESS_HOME   = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
	];
	CONST NUMBER_PHONE   = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
		self::INPUT_SANITIZER['CLEAN_NUM_INT'],
	];
	CONST EMAIL_ADDRESS   = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
		self::INPUT_SANITIZER['CLEAN_EMAIL'],
	];
	CONST EMAIL_SUBJECT   = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
		self::INPUT_SANITIZER['CLEAN_STRIPPED'],
		self::INPUT_SANITIZER['CLEAN_ENCODING'],
	];
	CONST EMAIL_MESSAGE   = [
		self::INPUT_SANITIZER['CLEAN_MAGIC_QUOTES'],
		self::INPUT_SANITIZER['CLEAN_SPEC_CHARS_FULL'],
		self::INPUT_SANITIZER['CLEAN_STRIPPED'],
		self::INPUT_SANITIZER['CLEAN_ENCODING'],		
	];
}//end class